### ISSUE TITLE
Joining server

### ISSUE THREAD

**Issue by ElecTwix** [go-mc/server#3]
![](https://i.imgur.com/qtbciL1.png)

When joining the server, giving level error
I created a level from 1.19.4 and put it in the same folder and 

I replaced ip and port with a placeholder to post.
```toml
listen-address="ip:port"
max-players=10
online-mode=false
```

**Comment by Tnze** [comment]
```toml
max-players = 20
listen-address = "127.0.0.1:25565"
motd = "A Minecraft Server - Written in Go"
online-mode = true
level-name = "world"
enforce-secure-profile = false
view-distance = 10
network-compression-threshold = 256

chunk-loading-limiter = { every = "20ms", n = 200 }
player-chunk-loading-limiter = { every = "20ms", n = 5 }
```
